# Generated by Django 5.2.17 on 2026-08-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('website', 'Website'), ('feed', 'RSS / Data Feed'), ('manual', 'Manual Entry')], default='website', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('domain', 'Research Domain'), ('method', 'Method / Technology'), ('purpose', 'Purpose'), ('career', 'Career Stage'), ('other', 'Other')], default='domain', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('opportunity_type', models.CharField(choices=[('research', 'Research Grant'), ('fellowship', 'Fellowship'), ('education', 'Education Grant'), ('equipment', 'Equipment / Research Resources'), ('travel', 'Travel Award'), ('training', 'Training Program'), ('other', 'Other')], default='research', max_length=30)),
                ('status', models.CharField(choices=[('forecasted', 'Forecasted'), ('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('award_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('award_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eligibility_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunities.source')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunities.sponsor')),
                ('tags', models.ManyToManyField(blank=True, related_name='opportunities', to='opportunities.tag')),
            ],
        ),
    ]
