# Generated by Django 5.2.17 on 2026-08-25 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.CreateModel(
            name='OpportunityCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(help_text='Example: 2027, Fall 2027, FY2028', max_length=100)),
                ('status', models.CharField(choices=[('forecasted', 'Forecasted'), ('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('award_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('award_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='opportunities.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_type', models.CharField(choices=[('loi', 'Letter of Intent'), ('preproposal', 'Preproposal'), ('application', 'Full Application'), ('nomination', 'Nomination'), ('rolling', 'Rolling Deadline'), ('other', 'Other')], default='application', max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='opportunities.opportunitycycle')),
            ],
        ),
    ]
