# Generated by Django 5.2.17 on 2026-08-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_options_opportunitycycle_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='recurrence_notes',
            field=models.CharField(blank=True, help_text='Example: Usually opens each spring.', max_length=300),
        ),
        migrations.AddField(
            model_name='opportunitycycle',
            name='award_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum project duration in months.', null=True),
        ),
        migrations.AddField(
            model_name='opportunitycycle',
            name='cost_share_required',
            field=models.BooleanField(blank=True, help_text='Leave unknown if the solicitation is unclear.', null=True),
        ),
        migrations.AddField(
            model_name='opportunitycycle',
            name='external_id',
            field=models.CharField(blank=True, help_text='Agency or source identifier, such as a Grants.gov Opportunity Number.', max_length=150),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('federal', 'Federal Agency'), ('state', 'State / Local Government'), ('foundation', 'Foundation'), ('society', 'Professional Society'), ('industry', 'Industry / Company'), ('university', 'University / Internal'), ('nonprofit', 'Nonprofit Organization'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='EligibilityCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('criterion_type', models.CharField(choices=[('applicant', 'Applicant Type'), ('career', 'Career Stage'), ('organization', 'Organization Type'), ('citizenship', 'Citizenship / Residency'), ('geography', 'Geographic Eligibility'), ('institution', 'Institution Requirement'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('criterion_type', 'name'),
                'constraints': [models.UniqueConstraint(fields=('criterion_type', 'name'), name='unique_eligibility_criterion')],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='eligibility_criteria',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='opportunities.eligibilitycriterion'),
        ),
    ]
