# Generated by Django 5.2.17 on 2026-09-08 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_importrun_sourcerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_version', models.CharField(default='rules-v1', max_length=32)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('suggestions', models.JSONField(default=list)),
                ('classified_at', models.DateTimeField(auto_now=True)),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_result', to='opportunities.sourcerecord')),
            ],
        ),
    ]
