# Generated by Django 5.2.17 on 2026-09-08 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_classificationresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_name', models.CharField(max_length=100)),
                ('suggestion_category', models.CharField(max_length=50)),
                ('evidence', models.JSONField(default=list)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_reviews', to='opportunities.sourcerecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_record', 'suggestion_name', 'suggestion_category'), name='unique_classification_review')],
            },
        ),
    ]
