# Generated by Django 5.2.17 on 2026-09-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_pipelinerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='coverage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
