# Generated by Django 5.2.17 on 2026-09-28 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_importrun_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Short internal identifier, such as plant-genomics-pathology.', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ResearchProfileWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('domain', 'Research Domain'), ('method', 'Method / Technology'), ('purpose', 'Purpose'), ('career', 'Career Stage'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Higher numbers mean a stronger relevance signal. These are ranking points, not probabilities.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='opportunities.researchprofile')),
            ],
            options={
                'ordering': ('profile', 'category', 'name'),
                'constraints': [models.UniqueConstraint(fields=('profile', 'category', 'name'), name='unique_research_profile_weight')],
            },
        ),
    ]
