# Generated by Django 5.2.17 on 2026-09-28 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_researchprofile_researchprofileweight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprofile',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Starter profile available for users to copy into their own account.'),
        ),
        migrations.AddField(
            model_name='researchprofile',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this profile. Starter templates do not have an owner.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchprofile',
            name='is_default',
            field=models.BooleanField(default=False, help_text="For user-owned profiles, indicates the user's default research profile."),
        ),
        migrations.AlterField(
            model_name='researchprofile',
            name='key',
            field=models.SlugField(help_text='Internal identifier such as plant-genomics-pathology.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='researchprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_template', True)), fields=('key',), name='unique_research_profile_template_key'),
        ),
        migrations.AddConstraint(
            model_name='researchprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_template', False), ('owner__isnull', False)), fields=('owner', 'key'), name='unique_user_research_profile_key'),
        ),
    ]
